config/routes.rb
Rails.application.routes.draw do
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
	has_many :declension_names
end

app/models/declension_name.rb
class DeclensionName < ApplicationRecord
	has_one :person
	has_one :case
end

app/models/person.rb
class Person < ApplicationRecord

  has_many :declension_names

  before_create do
    self.full_name = "#{self.first_name} #{self.midle_name} #{self.last_name}"
  end

  after_create :create_full_name_case
  after_save :update_full_name_case

  private
    def create_full_name_case
      Case.all.each do |c|
        self.declension_names.create(full_name: Petrovich(
          firstname: self.first_name,
          middlename: self.midle_name,
          lastname: self.last_name    
        ).send(c.method).to_s, case_id: c.id)
      end
    end

    def update_full_name_case
      self.declension_names.each do |dn|
        dn.update(full_name: Petrovich(
          firstname: self.first_name,
          middlename: self.midle_name,
          lastname: self.last_name
        ).send(Case.find(dn.case_id).method).to_s)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @cases = Case.all
    @full_name_cases = @person.declension_names
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :midle_name, :last_name, :sex, :full_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= simple_form_for @person do |f| %>
  <%= f.input :first_name %>
  <%= f.input :midle_name %>
  <%= f.input :last_name %>
  <%= f.input :sex, as: :select, collection: [[1, 'Male'],[ 0, "Female"]], label_method: :second, value_method: :first%>
  <%= f.button :submit %>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Midle name</th>
      <th>Last name</th>
      <th>Sex</th>
      <th>Full name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.midle_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.sex %></td>
        <td><%= person.full_name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Midle name:</strong>
  <%= @person.midle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @person.sex ? "Male" : "Female" %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @person.full_name %>
</p>

<table>
  <thead>
    <% @cases.each do |c| %>
      <th><%= c.name %></th>
    <% end %>
  </thead>
  <tbody>
    <% @full_name_cases.each do |fnc| %>
      <td><%= fnc.full_name %></td>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>